//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointment
    {
        public int appointmentID { get; set; }
        public string appointmentno { get; set; }
        public string staffID { get; set; }
        public Nullable<System.DateTime> appointmentdate { get; set; }
        public string personname { get; set; }
        public string purpose { get; set; }
        public string contactnumber { get; set; }
        public string time { get; set; }
    }
}
