//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESIS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class school_detailsEntities8 : DbContext
    {
        public school_detailsEntities8()
            : base("name=school_detailsEntities8")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<academicyear> academicyears { get; set; }
        public DbSet<appointment> appointments { get; set; }
        public DbSet<billingcycle> billingcycles { get; set; }
        public DbSet<feesstructure> feesstructures { get; set; }
        public DbSet<guardiandetail> guardiandetails { get; set; }
        public DbSet<stream> streams { get; set; }
        public DbSet<studentattendance> studentattendances { get; set; }
        public DbSet<student> students { get; set; }
        public DbSet<teacherattendance> teacherattendances { get; set; }
        public DbSet<transactionhistory> transactionhistories { get; set; }
        public DbSet<typeclass> typeclasses { get; set; }
        public DbSet<user_role> user_role { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<visitorpass> visitorpasses { get; set; }
    }
}
