//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class teacherattendance
    {
        public int no { get; set; }
        public System.DateTime attendanceDate { get; set; }
        public string TeacherNo { get; set; }
        public string status { get; set; }
        public System.DateTime dateRecorded { get; set; }
    }
}
